# Generated by Django 3.2.5 on 2021-07-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projetos',
            fields=[
                ('numero_projeto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome_projeto', models.CharField(max_length=30)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
    ]
