# Generated by Django 3.2.5 on 2021-07-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetos',
            name='data_fim',
            field=models.DateField(verbose_name='Data Fim'),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='data_inicio',
            field=models.DateField(verbose_name='Data Inicio'),
        ),
    ]
