# Generated by Django 3.2.5 on 2021-07-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_auto_20210720_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(verbose_name='Data Inicio')),
                ('data_fim', models.DateField(verbose_name='Data Fim')),
                ('situacao', models.BooleanField(default=True)),
                ('id_projeto', models.ManyToManyField(related_name='projetos', to='projects.Projetos')),
            ],
        ),
    ]
